{
  description = "Decision Graph — markdown-as-database CLI (dg) and MCP server (dg-mcp)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    bun2nix = {
      url = "github:nix-community/bun2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, bun2nix }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      version = (builtins.fromTOML (builtins.readFile ./Cargo.toml)).workspace.package.version;
      forAllSystems = f: nixpkgs.lib.genAttrs systems (system:
        f (import nixpkgs {
          inherit system;
          overlays = [ self.overlays.default ];
        }));

      # SvelteKit SPA, built offline: ui/bun.nix (generated by bun2nix from
      # ui/bun.lock) pins every npm tarball so the sandbox never needs the network.
      mkUi = pkgs: pkgs.stdenv.mkDerivation {
        pname = "dg-ui";
        inherit version;
        src = ./ui;
        nativeBuildInputs = [ pkgs.bun2nix.hook ];
        bunDeps = pkgs.bun2nix.fetchBunDeps { bunNix = ./ui/bun.nix; };
        buildPhase = ''
          runHook preBuild
          bun run build
          runHook postBuild
        '';
        installPhase = ''
          runHook preInstall
          cp -r build $out
          runHook postInstall
        '';
      };

      mkDg = pkgs: pkgs.rustPlatform.buildRustPackage {
        pname = "dg";
        inherit version;
        src = self;
        cargoLock = {
          lockFile = ./Cargo.lock;
          # graphs-tui comes from a git branch via [patch.crates-io]
          allowBuiltinFetchGit = true;
        };
        # Only ship the user-facing binaries, not workspace demo bins
        cargoBuildFlags = [ "--package" "dg-cli" "--package" "dg-mcp" ];
        # git2 pulls in vendored-openssl, whose build scripts need perl
        nativeBuildInputs = [ pkgs.perl ];
        buildInputs = pkgs.lib.optionals pkgs.stdenv.isDarwin [ pkgs.libiconv ];
        # The SPA is prebuilt as its own derivation; skip build.rs's bun step
        # and drop the result where rust-embed expects it (same trick as release.yml).
        DG_SKIP_UI_BUILD = "1";
        postPatch = ''
          cp -r ${mkUi pkgs} ui/build
          chmod -R u+w ui/build
        '';
        # Tests run in CI; skip them here to keep consumer installs fast
        doCheck = false;
        meta = {
          description = "Decision Graph — markdown-as-database CLI and MCP server";
          homepage = "https://github.com/decisiongraph/dg";
          mainProgram = "dg";
        };
      };
    in
    {
      overlays.default = nixpkgs.lib.composeExtensions
        bun2nix.overlays.default
        (final: prev: { dg = mkDg final; });

      packages = forAllSystems (pkgs: {
        dg = pkgs.dg;
        dg-ui = mkUi pkgs;
        # Pinned bun2nix CLI so `nix run .#bun2nix` regenerates ui/bun.nix
        # with the same version CI checks against.
        bun2nix = pkgs.bun2nix;
        default = pkgs.dg;
      });
    };
}
